"""AI-assisted generation engine for Brisk risk/control tracker output.

Uses LLM when configured, otherwise falls back to deterministic extraction
from pasted vendor evidence.
"""

from __future__ import annotations

import json
import os
import re
from datetime import date, timedelta
from typing import Any

SEVERITY_ORDER = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}
CONTROL_STATUSES = {
    "in progress": "In Progress",
    "in place": "In Place",
    "deferred": "Deferred",
    "unavailable": "Unavailable",
    "waived": "Waived",
    "not applicable": "Not Applicable",
    "postponed": "Deferred",
}

DEFAULT_RISKS = [
    {
        "risk_id": "R-001",
        "title": "Identity and access control gaps",
        "description": "Weak identity federation and access lifecycle controls can create unauthorized access risk.",
        "severity": "HIGH",
        "potential_impact": "Data exposure and unauthorized usage of enterprise AI capabilities.",
    },
    {
        "risk_id": "R-002",
        "title": "Audit and compliance evidence gaps",
        "description": "Missing audit APIs or insufficient logs can prevent compliance attestation and incident reconstruction.",
        "severity": "HIGH",
        "potential_impact": "Inability to satisfy SOX/HIPAA/PCI evidence requirements.",
    },
    {
        "risk_id": "R-003",
        "title": "Data egress and content control limitations",
        "description": "Insufficient egress filtering and DLP may allow uncontrolled sensitive data movement.",
        "severity": "MEDIUM",
        "potential_impact": "Data leakage or policy violations due to weak governance controls.",
    },
]


def normalize_status(raw: str) -> str:
    cleaned = re.sub(r"\s+", " ", raw.strip().lower())
    return CONTROL_STATUSES.get(cleaned, "In Progress")


def _infer_risks_from_controls(controls: list[dict[str, str]]) -> list[dict[str, str]]:
    risks = DEFAULT_RISKS.copy()
    text = " ".join(
        c.get("control_name", "").lower() + " " + c.get("status_rationale", "").lower()
        for c in controls
    )

    if "audit" in text or "compliance api" in text:
        risks[1]["severity"] = "CRITICAL"
        risks[1]["potential_impact"] = "Regulatory non-compliance and inability to investigate incidents."
    if "web search" in text or "egress" in text or "dlp" in text:
        risks[2]["severity"] = "HIGH"

    return risks


def _due_date_for_severity(severity: str) -> str:
    days = {"CRITICAL": 30, "HIGH": 30, "MEDIUM": 60, "LOW": 90}[severity]
    return str(date.today() + timedelta(days=days))


def _parse_control_rows(evidence_text: str) -> list[dict[str, str]]:
    controls: list[dict[str, str]] = []
    for line in evidence_text.splitlines():
        line = line.strip()
        if not line or line.lower().startswith("control"):
            continue

        # Try pipe-delimited row first.
        if "|" in line:
            parts = [p.strip() for p in line.split("|") if p.strip()]
            if len(parts) >= 4:
                controls.append(
                    {
                        "control_name": parts[0],
                        "what_it_does": parts[1],
                        "how_to_deploy": parts[2],
                        "status": normalize_status(parts[3]),
                        "notes": "",
                    }
                )
                continue

        # Fallback for free text rows ending in known statuses.
        match = re.search(r"\b(In Progress|In Place|Deferred|Unavailable|Waived|Not Applicable)\b$", line, flags=re.I)
        if match:
            status = normalize_status(match.group(1))
            control_name = re.sub(r"\b(In Progress|In Place|Deferred|Unavailable|Waived|Not Applicable)\b$", "", line, flags=re.I).strip(" -:")
            controls.append(
                {
                    "control_name": control_name or "Unspecified control",
                    "what_it_does": "See evidence text",
                    "how_to_deploy": "To be defined",
                    "status": status,
                    "notes": "",
                }
            )

    if not controls:
        controls = [
            {
                "control_name": "SSO/SAML/SCIM",
                "what_it_does": "Ties access to corporate identity.",
                "how_to_deploy": "Standard IdP integration",
                "status": "In Progress",
                "notes": "Autogenerated fallback because no structured controls were parsed.",
            }
        ]

    normalized_controls = []
    for idx, control in enumerate(controls, start=1):
        normalized_controls.append(
            {
                "control_id": f"C-{idx:03d}",
                "related_risk_ids": ["R-001"],
                "control_name": control["control_name"],
                "description": control["what_it_does"],
                "deployment_guidance": control["how_to_deploy"],
                "status": control["status"],
                "owner": "Unassigned",
                "due_date": _due_date_for_severity("HIGH"),
                "status_rationale": control["notes"],
            }
        )

    return normalized_controls


def _attach_risk_links(controls: list[dict[str, Any]]) -> None:
    for control in controls:
        name = (control.get("control_name") or "").lower()
        if any(term in name for term in ["audit", "compliance", "log"]):
            control["related_risk_ids"] = ["R-002"]
        elif any(term in name for term in ["network", "dlp", "domain", "egress", "search"]):
            control["related_risk_ids"] = ["R-003"]
        else:
            control["related_risk_ids"] = ["R-001"]


def generate_assessment(vendor_name: str, vendor_type: str, evidence_text: str) -> dict[str, Any]:
    controls = _parse_control_rows(evidence_text)
    _attach_risk_links(controls)
    risks = _infer_risks_from_controls(controls)

    highest = max((risk["severity"] for risk in risks), key=lambda s: SEVERITY_ORDER[s])

    return {
        "vendor": {
            "name": vendor_name,
            "vendor_type": vendor_type,
            "business_owner": "Unassigned",
            "data_classification": "To be determined",
        },
        "vendor_service_description": (
            f"{vendor_name} is assessed as a {vendor_type} vendor. "
            "This assessment was generated from provided evidence and should be reviewed by Security and Business owners."
        ),
        "risks": risks,
        "controls": controls,
        "assignment_and_tracking": {
            "assigned_to": "Unassigned - To be assigned to Block team member",
            "created_date": str(date.today()),
            "status": "Open - Pending Review",
            "recommended_due_date": _due_date_for_severity(highest),
        },
        "open_questions": [
            "Confirm whether audit logs are exportable to Block SIEM.",
            "Confirm compliance scope and contractual commitments for unavailable controls.",
        ],
        "assumptions": [
            "Status values were inferred from submitted evidence text.",
            "Control ownership defaults to Unassigned until business owner assignment.",
        ],
    }


def maybe_generate_with_llm(vendor_name: str, vendor_type: str, evidence_text: str) -> dict[str, Any]:
    """Use LLM if configured; fallback to deterministic generation."""
    api_key = os.getenv("OPENAI_API_KEY")
    model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
    if not api_key:
        return generate_assessment(vendor_name, vendor_type, evidence_text)

    try:
        from openai import OpenAI  # type: ignore

        client = OpenAI(api_key=api_key)
        prompt = (
            "Return only JSON with keys vendor, vendor_service_description, risks, controls, "
            "assignment_and_tracking, open_questions, assumptions. "
            f"Vendor: {vendor_name} ({vendor_type}). Evidence:\n{evidence_text}"
        )
        resp = client.responses.create(model=model, input=prompt)
        text = resp.output_text
        return json.loads(text)
    except Exception:
        return generate_assessment(vendor_name, vendor_type, evidence_text)
